apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ssl-cert-spotify-profile-frontend
  namespace: prod
spec:
  secretName: ssl-cert-spotify-profile-frontend
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - spotify-profile.julienprr.com
    - www.spotify-profile.julienprr.com
