apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spotify-profile-frontend-ingress
  namespace: prod
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - spotify-profile.julienprr.com
        - www.spotify-profile.julienprr.com
      secretName: ssl-cert-spotify-profile-frontend
  rules:
    - host: spotify-profile.julienprr.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spotify-profile-frontend
                port:
                  number: 80
    - host: www.spotify-profile.julienprr.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spotify-profile-frontend
                port:
                  number: 80
