apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kibana-cert
  namespace: logging
spec:
  secretName: kibana-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: kibana.julienprr.com
  dnsNames:
    - kibana.julienprr.com
  usages:
    - digital signature
    - key encipherment
