apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ssl-cert-play-manager-frontend
  namespace: dev
spec:
  secretName: ssl-cert-play-manager-frontend
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
    - dev.play-manager.julienprr.com
    - www.dev.play-manager.julienprr.com
