daemonset:
  enabled: true

filebeatConfig:
  filebeat.yml: |
    filebeat.autodiscover:
      providers:
        - type: kubernetes
          node: ${NODE_NAME}
          hints.enabled: true

    processors:
      - add_cloud_metadata: ~
      - add_host_metadata: ~

    output.elasticsearch:
      hosts: ["http://elasticsearch-master.logging.svc.cluster.local:9200"]
