apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ssl-cert-play-manager-backend
  namespace: prod
spec:
  secretName: ssl-cert-play-manager-backend
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - play-manager-api.julienprr.com
    - www.play-manager.julienprr.com
