apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portfolio
  namespace: prod
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - julienprr.com
        - www.julienprr.com
      secretName: ssl-cert-production
  rules:
    - host: julienprr.com
      http:
        paths:
          - path: /.well-known/acme-challenge/
            pathType: Prefix
            backend:
              service:
                name: portfolio
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: portfolio
                port:
                  number: 80
    - host: www.julienprr.com
      http:
        paths:
         - path: /.well-known/acme-challenge/
           pathType: Prefix
           backend:
             service:
               name: portfolio
               port:
                 number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: portfolio
                port:
                  number: 80
