apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ssl-cert-dev
  namespace: dev
spec:
  secretName: ssl-cert-dev
  issuerRef:
    name: letsencrypt-produduction
    kind: ClusterIssuer
  commonName: dev.julienprr.com
  dnsNames:
    - dev.julienprr.com
    - www.dev.julienprr.com
    - dev.portfolio.julienprr.com
    - www.dev.portfolio.julienprr.com
