apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ssl-cert-production
  namespace: prod
spec:
  secretName: ssl-cert-production
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: julienprr.com
  dnsNames:
    - julienprr.com
    - www.julienprr.com
    - portfolio.julienprr.com
    - play-manager-api.julienprr.com
    - play-manager.julienprr.com
