apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ssl-cert-staging
  namespace: dev
spec:
  secretName: ssl-cert-staging
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: dev.julienprr.com
  dnsNames:
    - dev.julienprr.com
    - www.dev.julienprr.com
    - dev.portfolio.julienprr.com
    - dev.play-manager-api.julienprr.com
    - dev.play-manager.julienprr.com
